version: '3.8'

services:
  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=
      - PORT=8000
      - JWT_SECRET=your_jwt_secret_here
      - JWT_EXPIRY=1h
      - GEMINI_API_KEY=your_gemini_api_key_here
      - ADMIN_PASSWORD_HASH=your_admin_password_hash_here
    volumes:
      - .:/app
    restart: unless-stopped
